### ISSUE TITLE
heroku local does not work

### ISSUE THREAD

**Issue by zelark** [J3FALL/FindBuddy#13]
```
moon:FindBuddy lark$ heroku local
[WARN] Cannot read property '1' of null
[FAIL] No Procfile and no package.json file found in Current Directory - See heroku local --help
 ▸    Cannot convert undefined or null to object
```

`heroku local` — команда, которая позволяет запустить проект локально, но как-будто это происходит на хероку.

Для того чтобы это успешно заработало:
1. Должен быть валидный Procfile, текущий имеет ошибку в синтаксисе, пропущен символ «:» после слова web;
2. В корне проекта также должен лежать .env файл со строками вида key=value. Для текущего проекта туда необходимо положить ключи DATABASE_URL и PORT. Не забыть при этом добавить файл .env в .gitignore.

Предлагаю оформить этот баг в виде пул реквеста. Я сделаю ревью и солью его в develop.

**Comment by LennyKhusaenov** [comment]
https://github.com/J3FALL/FindBuddy/commit/71090ce6c4ea628d01b28c719db186aa406193e5
https://github.com/J3FALL/FindBuddy/commit/98ee50763a97e12e1d9e933f3a200be0d41e35d1
